version: '1.0.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build:
  project: System.Data.Async.sln
  verbosity: minimal
test_script:
- cmd: dotnet test Samples/Moq/Moq.csproj
artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages
deploy:
- provider: NuGet
  api_key:
    secure: 3dh7pjPch1zd1E5C55zjjSUs1qnF6vDVovOY0TjVKit9G/5mRqEUOnBz2cJ6Sz+m
  on:
    branch: master