image: Visual Studio 2017
configuration: Release
version: '{build}'

install:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false")
    {
      $env:COMMIT_DESCRIPTION = git describe --tags
    }
    else
    {
      $env:COMMIT_DESCRIPTION = $env:APPVEYOR_REPO_TAG_NAME
    }
    Write-Host Build version is $env:COMMIT_DESCRIPTION

dotnet_csproj:
  patch: true
  file: 'System.Data.Async\System.Data.Async.csproj'
  version: $(commit_description)

before_build:
- cmd: dotnet restore

build:
  project: System.Data.Async.sln

test_script:
- cmd: >-
    dotnet test Samples/Moq/Moq.csproj

    dotnet test Samples/LocalDb/LocalDb.csproj

artifacts:
- path: '**/*.nupkg'
  name: Nuget Packages

deploy:
- provider: NuGet
  api_key:
    secure: 3dh7pjPch1zd1E5C55zjjSUs1qnF6vDVovOY0TjVKit9G/5mRqEUOnBz2cJ6Sz+m
  on:
    appveyor_repo_tag: true
